import { Orbitron } from "next/font/google";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";

const orbitronFont = Orbitron({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "400"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${orbitronFont.className}`}>
        <HeroUIProvider>{children}</HeroUIProvider>
      </body>
    </html>
  );
}
